spring.datasource.driver-class-name=org.postgresql.Driver
spring.application.name=TaskManager
spring.datasource.url=jdbc:postgresql://localhost:5432/taskdb
spring.datasource.username=postgres
spring.datasource.password=test
spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.web.error.include-stacktrace=never
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
